import { Parser } from 'json2csv';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { config } from '../config/env.js';
import fs from 'fs';
import path from 'path';

function safeName(name) {
  return String(name).replace(/[^a-z0-9-_]/gi, '_').toLowerCase();
}

export async function exportData({ format = 'json', fileName, title, meta, rows, sheets }) {
  const dir = config.exportDir;
  fs.mkdirSync(dir, { recursive: true });
  const base = safeName(fileName || title || 'report');
  const filePath = path.join(dir, `${base}.${format === 'xlsx' ? 'xlsx' : format}`);

  switch (format) {
    case 'csv': {
      const parser = new Parser({ flatten: true });
      fs.writeFileSync(filePath, parser.parse(rows || []));
      break;
    }
    case 'json': {
      fs.writeFileSync(filePath, JSON.stringify({ title, meta, rows, generatedAt: new Date().toISOString() }, null, 2));
      break;
    }
    case 'xlsx': {
      const wb = new ExcelJS.Workbook();
      const ws = wb.addWorksheet('Report');
      ws.columns = [
        { header: 'Section', key: 'section', width: 30 },
        { header: 'Field', key: 'field', width: 28 },
        { header: 'Value', key: 'value', width: 70 },
      ];
      ws.addRow({ section: 'REPORT', field: 'Title', value: title });
      ws.addRow({ section: 'REPORT', field: 'Generated', value: new Date().toISOString() });
      if (meta) {
        for (const [k, v] of Object.entries(meta)) {
          ws.addRow({ section: 'META', field: k, value: typeof v === 'object' ? JSON.stringify(v) : String(v) });
        }
      }
      const detail = wb.addWorksheet('Detail');
      if (rows && rows.length) {
        detail.columns = Object.keys(rows[0]).map((k) => ({ header: k, key: k, width: 24 }));
        rows.forEach((r) => detail.addRow(r));
      }
      if (sheets) {
        for (const [sheetName, sheetRows] of Object.entries(sheets)) {
          const s = wb.addWorksheet(String(sheetName).slice(0, 31));
          if (sheetRows && sheetRows.length) {
            s.columns = Object.keys(sheetRows[0]).map((k) => ({ header: k, key: k, width: 24 }));
            sheetRows.forEach((r) => s.addRow(r));
          }
        }
      }
      await wb.xlsx.writeFile(filePath);
      break;
    }
    case 'pdf': {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);
      doc.fontSize(18).text(title || 'OneRecon Report', { underline: true });
      doc.moveDown();
      doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`);
      if (meta) {
        doc.moveDown();
        doc.fontSize(11).text('Summary');
        doc.moveDown(0.5);
        for (const [k, v] of Object.entries(meta)) {
          doc.fontSize(9).text(`${k}: ${typeof v === 'object' ? JSON.stringify(v) : v}`);
        }
      }
      if (rows && rows.length) {
        doc.moveDown();
        doc.fontSize(11).text('Detail');
        doc.moveDown(0.5);
        const keys = Object.keys(rows[0]);
        const colW = 500 / Math.min(keys.length, 6);
        keys.slice(0, 6).forEach((k) => doc.fontSize(7).text(`${k}`.toUpperCase(), { continued: true, width: colW }));
        doc.moveDown(0.25);
        rows.slice(0, 400).forEach((r) => {
          keys.slice(0, 6).forEach((k) => {
            const v = r[k];
            doc.fontSize(6.5).text(v == null ? '' : String(v).slice(0, 40), { continued: true, width: colW });
          });
          doc.moveDown(0.15);
        });
        if (rows.length > 400) doc.fontSize(8).text(`… ${rows.length - 400} more rows truncated in PDF (use Excel for full data)`);
      }
      doc.fontSize(7).text('\nFinal decisions rest with authorized personnel. Report generated by OneRecon.', { align: 'center' });
      doc.end();
      await new Promise((resolve) => stream.on('close', resolve));
      break;
    }
    default:
      throw new Error(`Unsupported format: ${format}`);
  }
  return filePath;
}